### ISSUE TITLE
type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast

### ISSUE THREAD

**Issue by realkimmy** [neckaros/secure_application#19]
```
flutter: [debug] Capture from onError type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building SecureGate(dirty, dependencies: [_EffectiveTickerMode, SecureApplicationProvider], state: _SecureGateState#93e4b(ticker inactive)):
type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast

The relevant error-causing widget was: 
  SecureGate file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:297:21
When the exception was thrown, this was the stack: 
#0      _SecureGateState.build (package:secure_application/secure_gate.dart:118:9)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
...
====================================================================================================
```

**Comment by rasouliali1379** [comment]
I got same error

**Comment by Rodsevich** [comment]
The PR pending are fixes to this very issue

**Comment by chulster** [comment]
Are the fixes working?

**Comment by Rodsevich** [comment]
yeah, like a charm

**Comment by neckaros** [comment]
i will merge it thanks

**Comment by neckaros** [comment]
Published to Pub.dev
Please reopen the issue if it is not well corrected!
Thanks!
